//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.23 at 11:54:31 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for Annotation type
 * 
 * <p>Java class for AnnotationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnnotationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{spdx:xsd::1.0}Date"/>
 *         &lt;element ref="{spdx:xsd::1.0}AnnotationTypeCode"/>
 *         &lt;element ref="{spdx:xsd::1.0}Comment"/>
 *         &lt;element ref="{spdx:xsd::1.0}Annotator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnnotationType", propOrder = {
    "date",
    "annotationTypeCode",
    "comment",
    "annotator"
})
public class Annotation {

    @XmlElement(name = "Date", required = true, nillable = true)
    protected Date date;
    @XmlElement(name = "AnnotationTypeCode", required = true, nillable = true)
    protected AnnotationTypeCode annotationTypeCode;
    @XmlElement(name = "Comment", required = true, nillable = true)
    protected Comment comment;
    @XmlElement(name = "Annotator", required = true, nillable = true)
    protected Annotator annotator;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDate(Date value) {
        this.date = value;
    }

    /**
     * Gets the value of the annotationTypeCode property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationTypeCode }
     *     
     */
    public AnnotationTypeCode getAnnotationTypeCode() {
        return annotationTypeCode;
    }

    /**
     * Sets the value of the annotationTypeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationTypeCode }
     *     
     */
    public void setAnnotationTypeCode(AnnotationTypeCode value) {
        this.annotationTypeCode = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the annotator property.
     * 
     * @return
     *     possible object is
     *     {@link Annotator }
     *     
     */
    public Annotator getAnnotator() {
        return annotator;
    }

    /**
     * Sets the value of the annotator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Annotator }
     *     
     */
    public void setAnnotator(Annotator value) {
        this.annotator = value;
    }

}
