//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.23 at 11:54:31 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for CreationInfo type
 * 
 * <p>Java class for CreationInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CreationInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{spdx:xsd::1.0}LicenseListVersion" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}Created"/>
 *         &lt;element ref="{spdx:xsd::1.0}Comment" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}Creator"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CreationInfoType", propOrder = {
    "licenseListVersion",
    "created",
    "comment",
    "creator"
})
public class CreationInfo {

    @XmlElement(name = "LicenseListVersion", nillable = true)
    protected LicenseListVersion licenseListVersion;
    @XmlElement(name = "Created", required = true, nillable = true)
    protected Created created;
    @XmlElement(name = "Comment", nillable = true)
    protected Comment comment;
    @XmlElement(name = "Creator", required = true, nillable = true)
    protected Creator creator;

    /**
     * Gets the value of the licenseListVersion property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseListVersion }
     *     
     */
    public LicenseListVersion getLicenseListVersion() {
        return licenseListVersion;
    }

    /**
     * Sets the value of the licenseListVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseListVersion }
     *     
     */
    public void setLicenseListVersion(LicenseListVersion value) {
        this.licenseListVersion = value;
    }

    /**
     * Gets the value of the created property.
     * 
     * @return
     *     possible object is
     *     {@link Created }
     *     
     */
    public Created getCreated() {
        return created;
    }

    /**
     * Sets the value of the created property.
     * 
     * @param value
     *     allowed object is
     *     {@link Created }
     *     
     */
    public void setCreated(Created value) {
        this.created = value;
    }

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link Comment }
     *     
     */
    public Comment getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Comment }
     *     
     */
    public void setComment(Comment value) {
        this.comment = value;
    }

    /**
     * Gets the value of the creator property.
     * 
     * @return
     *     possible object is
     *     {@link Creator }
     *     
     */
    public Creator getCreator() {
        return creator;
    }

    /**
     * Sets the value of the creator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Creator }
     *     
     */
    public void setCreator(Creator value) {
        this.creator = value;
    }

}
