//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.23 at 11:54:31 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the spdx.xsd._1 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DescribesPackage_QNAME = new QName("spdx:xsd::1.0", "DescribesPackage");
    private final static QName _Checksum_QNAME = new QName("spdx:xsd::1.0", "Checksum");
    private final static QName _RelatedSpdxElement_QNAME = new QName("spdx:xsd::1.0", "RelatedSpdxElement");
    private final static QName _AlgorithmCode_QNAME = new QName("spdx:xsd::1.0", "AlgorithmCode");
    private final static QName _Creator_QNAME = new QName("spdx:xsd::1.0", "Creator");
    private final static QName _Annotator_QNAME = new QName("spdx:xsd::1.0", "Annotator");
    private final static QName _Comment_QNAME = new QName("spdx:xsd::1.0", "Comment");
    private final static QName _ExternalDocumentRef_QNAME = new QName("spdx:xsd::1.0", "ExternalDocumentRef");
    private final static QName _SpdxDocument_QNAME = new QName("spdx:xsd::1.0", "SpdxDocument");
    private final static QName _ExternalDocumentID_QNAME = new QName("spdx:xsd::1.0", "ExternalDocumentID");
    private final static QName _RelationshipTypeCode_QNAME = new QName("spdx:xsd::1.0", "RelationshipTypeCode");
    private final static QName _HasExtractedLicensingInfo_QNAME = new QName("spdx:xsd::1.0", "HasExtractedLicensingInfo");
    private final static QName _Name_QNAME = new QName("spdx:xsd::1.0", "Name");
    private final static QName _DescribesFile_QNAME = new QName("spdx:xsd::1.0", "DescribesFile");
    private final static QName _Created_QNAME = new QName("spdx:xsd::1.0", "Created");
    private final static QName _Date_QNAME = new QName("spdx:xsd::1.0", "Date");
    private final static QName _ChecksumValue_QNAME = new QName("spdx:xsd::1.0", "ChecksumValue");
    private final static QName _Annotation_QNAME = new QName("spdx:xsd::1.0", "Annotation");
    private final static QName _CreationInfo_QNAME = new QName("spdx:xsd::1.0", "CreationInfo");
    private final static QName _SpecVersion_QNAME = new QName("spdx:xsd::1.0", "SpecVersion");
    private final static QName _AnnotationTypeCode_QNAME = new QName("spdx:xsd::1.0", "AnnotationTypeCode");
    private final static QName _Relationship_QNAME = new QName("spdx:xsd::1.0", "Relationship");
    private final static QName _SpdxElement_QNAME = new QName("spdx:xsd::1.0", "SpdxElement");
    private final static QName _LicenseListVersion_QNAME = new QName("spdx:xsd::1.0", "LicenseListVersion");
    private final static QName _DataLicense_QNAME = new QName("spdx:xsd::1.0", "DataLicense");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: spdx.xsd._1
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Checksum }
     * 
     */
    public Checksum createChecksum() {
        return new Checksum();
    }

    /**
     * Create an instance of {@link Relationship }
     * 
     */
    public Relationship createRelationship() {
        return new Relationship();
    }

    /**
     * Create an instance of {@link Annotator }
     * 
     */
    public Annotator createAnnotator() {
        return new Annotator();
    }

    /**
     * Create an instance of {@link AlgorithmCode }
     * 
     */
    public AlgorithmCode createAlgorithmCode() {
        return new AlgorithmCode();
    }

    /**
     * Create an instance of {@link ExternalDocumentRef }
     * 
     */
    public ExternalDocumentRef createExternalDocumentRef() {
        return new ExternalDocumentRef();
    }

    /**
     * Create an instance of {@link RelationshipTypeCode }
     * 
     */
    public RelationshipTypeCode createRelationshipTypeCode() {
        return new RelationshipTypeCode();
    }

    /**
     * Create an instance of {@link SpdxDocument }
     * 
     */
    public SpdxDocument createSpdxDocument() {
        return new SpdxDocument();
    }

    /**
     * Create an instance of {@link Created }
     * 
     */
    public Created createCreated() {
        return new Created();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link ChecksumValue }
     * 
     */
    public ChecksumValue createChecksumValue() {
        return new ChecksumValue();
    }

    /**
     * Create an instance of {@link SpecVersion }
     * 
     */
    public SpecVersion createSpecVersion() {
        return new SpecVersion();
    }

    /**
     * Create an instance of {@link AnnotationTypeCode }
     * 
     */
    public AnnotationTypeCode createAnnotationTypeCode() {
        return new AnnotationTypeCode();
    }

    /**
     * Create an instance of {@link LicenseListVersion }
     * 
     */
    public LicenseListVersion createLicenseListVersion() {
        return new LicenseListVersion();
    }

    /**
     * Create an instance of {@link SpdxElement }
     * 
     */
    public SpdxElement createSpdxElement() {
        return new SpdxElement();
    }

    /**
     * Create an instance of {@link Creator }
     * 
     */
    public Creator createCreator() {
        return new Creator();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link ExternalDocumentID }
     * 
     */
    public ExternalDocumentID createExternalDocumentID() {
        return new ExternalDocumentID();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link CreationInfo }
     * 
     */
    public CreationInfo createCreationInfo() {
        return new CreationInfo();
    }

    /**
     * Create an instance of {@link Annotation }
     * 
     */
    public Annotation createAnnotation() {
        return new Annotation();
    }

    /**
     * Create an instance of {@link LicenseID }
     * 
     */
    public LicenseID createLicenseID() {
        return new LicenseID();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "DescribesPackage")
    public JAXBElement<SpdxDocument> createDescribesPackage(SpdxDocument value) {
        return new JAXBElement<SpdxDocument>(_DescribesPackage_QNAME, SpdxDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Checksum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Checksum")
    public JAXBElement<Checksum> createChecksum(Checksum value) {
        return new JAXBElement<Checksum>(_Checksum_QNAME, Checksum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Relationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "RelatedSpdxElement")
    public JAXBElement<Relationship> createRelatedSpdxElement(Relationship value) {
        return new JAXBElement<Relationship>(_RelatedSpdxElement_QNAME, Relationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AlgorithmCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "AlgorithmCode")
    public JAXBElement<AlgorithmCode> createAlgorithmCode(AlgorithmCode value) {
        return new JAXBElement<AlgorithmCode>(_AlgorithmCode_QNAME, AlgorithmCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Creator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Creator")
    public JAXBElement<Creator> createCreator(Creator value) {
        return new JAXBElement<Creator>(_Creator_QNAME, Creator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Annotator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Annotator")
    public JAXBElement<Annotator> createAnnotator(Annotator value) {
        return new JAXBElement<Annotator>(_Annotator_QNAME, Annotator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Comment }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Comment")
    public JAXBElement<Comment> createComment(Comment value) {
        return new JAXBElement<Comment>(_Comment_QNAME, Comment.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalDocumentRef }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "ExternalDocumentRef")
    public JAXBElement<ExternalDocumentRef> createExternalDocumentRef(ExternalDocumentRef value) {
        return new JAXBElement<ExternalDocumentRef>(_ExternalDocumentRef_QNAME, ExternalDocumentRef.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "SpdxDocument")
    public JAXBElement<SpdxDocument> createSpdxDocument(SpdxDocument value) {
        return new JAXBElement<SpdxDocument>(_SpdxDocument_QNAME, SpdxDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ExternalDocumentID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "ExternalDocumentID")
    public JAXBElement<ExternalDocumentID> createExternalDocumentID(ExternalDocumentID value) {
        return new JAXBElement<ExternalDocumentID>(_ExternalDocumentID_QNAME, ExternalDocumentID.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelationshipTypeCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "RelationshipTypeCode")
    public JAXBElement<RelationshipTypeCode> createRelationshipTypeCode(RelationshipTypeCode value) {
        return new JAXBElement<RelationshipTypeCode>(_RelationshipTypeCode_QNAME, RelationshipTypeCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "HasExtractedLicensingInfo")
    public JAXBElement<SpdxDocument> createHasExtractedLicensingInfo(SpdxDocument value) {
        return new JAXBElement<SpdxDocument>(_HasExtractedLicensingInfo_QNAME, SpdxDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Name }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Name")
    public JAXBElement<Name> createName(Name value) {
        return new JAXBElement<Name>(_Name_QNAME, Name.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxDocument }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "DescribesFile")
    public JAXBElement<SpdxDocument> createDescribesFile(SpdxDocument value) {
        return new JAXBElement<SpdxDocument>(_DescribesFile_QNAME, SpdxDocument.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Created }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Created")
    public JAXBElement<Created> createCreated(Created value) {
        return new JAXBElement<Created>(_Created_QNAME, Created.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Date }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Date")
    public JAXBElement<Date> createDate(Date value) {
        return new JAXBElement<Date>(_Date_QNAME, Date.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ChecksumValue }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "ChecksumValue")
    public JAXBElement<ChecksumValue> createChecksumValue(ChecksumValue value) {
        return new JAXBElement<ChecksumValue>(_ChecksumValue_QNAME, ChecksumValue.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Annotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Annotation")
    public JAXBElement<Annotation> createAnnotation(Annotation value) {
        return new JAXBElement<Annotation>(_Annotation_QNAME, Annotation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreationInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "CreationInfo")
    public JAXBElement<CreationInfo> createCreationInfo(CreationInfo value) {
        return new JAXBElement<CreationInfo>(_CreationInfo_QNAME, CreationInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpecVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "SpecVersion")
    public JAXBElement<SpecVersion> createSpecVersion(SpecVersion value) {
        return new JAXBElement<SpecVersion>(_SpecVersion_QNAME, SpecVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AnnotationTypeCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "AnnotationTypeCode")
    public JAXBElement<AnnotationTypeCode> createAnnotationTypeCode(AnnotationTypeCode value) {
        return new JAXBElement<AnnotationTypeCode>(_AnnotationTypeCode_QNAME, AnnotationTypeCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Relationship }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "Relationship")
    public JAXBElement<Relationship> createRelationship(Relationship value) {
        return new JAXBElement<Relationship>(_Relationship_QNAME, Relationship.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SpdxElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "SpdxElement")
    public JAXBElement<SpdxElement> createSpdxElement(SpdxElement value) {
        return new JAXBElement<SpdxElement>(_SpdxElement_QNAME, SpdxElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LicenseListVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "LicenseListVersion")
    public JAXBElement<LicenseListVersion> createLicenseListVersion(LicenseListVersion value) {
        return new JAXBElement<LicenseListVersion>(_LicenseListVersion_QNAME, LicenseListVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LicenseID }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "spdx:xsd::1.0", name = "DataLicense")
    public JAXBElement<LicenseID> createDataLicense(LicenseID value) {
        return new JAXBElement<LicenseID>(_DataLicense_QNAME, LicenseID.class, null, value);
    }

}
