//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.23 at 11:54:31 AM PDT 
//


package spdx.xsd._1;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A data type for SpdxDocument type
 * 
 * <p>Java class for SpdxDocumentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpdxDocumentType">
 *   &lt;complexContent>
 *     &lt;extension base="{spdx:xsd::1.0}SpdxElementType">
 *       &lt;sequence>
 *         &lt;element ref="{spdx:xsd::1.0}DescribesPackage" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}DescribesFile" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}HasExtractedLicensingInfo" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}CreationInfo"/>
 *         &lt;element ref="{spdx:xsd::1.0}SpecVersion"/>
 *         &lt;element ref="{spdx:xsd::1.0}ExternalDocumentRef" minOccurs="0"/>
 *         &lt;element ref="{spdx:xsd::1.0}DataLicense"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpdxDocumentType", propOrder = {
    "describesPackage",
    "describesFile",
    "hasExtractedLicensingInfo",
    "creationInfo",
    "specVersion",
    "externalDocumentRef",
    "dataLicense"
})
public class SpdxDocument
    extends SpdxElement
{

    @XmlElement(name = "DescribesPackage", nillable = true)
    protected SpdxDocument describesPackage;
    @XmlElement(name = "DescribesFile", nillable = true)
    protected SpdxDocument describesFile;
    @XmlElement(name = "HasExtractedLicensingInfo", nillable = true)
    protected SpdxDocument hasExtractedLicensingInfo;
    @XmlElement(name = "CreationInfo", required = true, nillable = true)
    protected CreationInfo creationInfo;
    @XmlElement(name = "SpecVersion", required = true, nillable = true)
    protected SpecVersion specVersion;
    @XmlElement(name = "ExternalDocumentRef", nillable = true)
    protected ExternalDocumentRef externalDocumentRef;
    @XmlElement(name = "DataLicense", required = true, nillable = true)
    protected LicenseID dataLicense;

    /**
     * Gets the value of the describesPackage property.
     * 
     * @return
     *     possible object is
     *     {@link SpdxDocument }
     *     
     */
    public SpdxDocument getDescribesPackage() {
        return describesPackage;
    }

    /**
     * Sets the value of the describesPackage property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpdxDocument }
     *     
     */
    public void setDescribesPackage(SpdxDocument value) {
        this.describesPackage = value;
    }

    /**
     * Gets the value of the describesFile property.
     * 
     * @return
     *     possible object is
     *     {@link SpdxDocument }
     *     
     */
    public SpdxDocument getDescribesFile() {
        return describesFile;
    }

    /**
     * Sets the value of the describesFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpdxDocument }
     *     
     */
    public void setDescribesFile(SpdxDocument value) {
        this.describesFile = value;
    }

    /**
     * Gets the value of the hasExtractedLicensingInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SpdxDocument }
     *     
     */
    public SpdxDocument getHasExtractedLicensingInfo() {
        return hasExtractedLicensingInfo;
    }

    /**
     * Sets the value of the hasExtractedLicensingInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpdxDocument }
     *     
     */
    public void setHasExtractedLicensingInfo(SpdxDocument value) {
        this.hasExtractedLicensingInfo = value;
    }

    /**
     * Gets the value of the creationInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CreationInfo }
     *     
     */
    public CreationInfo getCreationInfo() {
        return creationInfo;
    }

    /**
     * Sets the value of the creationInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CreationInfo }
     *     
     */
    public void setCreationInfo(CreationInfo value) {
        this.creationInfo = value;
    }

    /**
     * Gets the value of the specVersion property.
     * 
     * @return
     *     possible object is
     *     {@link SpecVersion }
     *     
     */
    public SpecVersion getSpecVersion() {
        return specVersion;
    }

    /**
     * Sets the value of the specVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecVersion }
     *     
     */
    public void setSpecVersion(SpecVersion value) {
        this.specVersion = value;
    }

    /**
     * Gets the value of the externalDocumentRef property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalDocumentRef }
     *     
     */
    public ExternalDocumentRef getExternalDocumentRef() {
        return externalDocumentRef;
    }

    /**
     * Sets the value of the externalDocumentRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalDocumentRef }
     *     
     */
    public void setExternalDocumentRef(ExternalDocumentRef value) {
        this.externalDocumentRef = value;
    }

    /**
     * Gets the value of the dataLicense property.
     * 
     * @return
     *     possible object is
     *     {@link LicenseID }
     *     
     */
    public LicenseID getDataLicense() {
        return dataLicense;
    }

    /**
     * Sets the value of the dataLicense property.
     * 
     * @param value
     *     allowed object is
     *     {@link LicenseID }
     *     
     */
    public void setDataLicense(LicenseID value) {
        this.dataLicense = value;
    }

}
